import {
  BoxSelect, Move3d, Rotate3d, Maximize2, Pencil, Shuffle,
  Orbit, Spline, Layers, GitBranch, Columns3, Diamond,
  Radius, PaintBucket, Shell, Waves, Drill, Ruler,
  Combine, CopyMinus, Crosshair, Component, CaseSensitive,
  WrapText, Split, Hand, Ban, Workflow, Shapes, Crop,
  Pyramid, Cog, Variable, Type, Rows3, Columns2, AlignCenter,
  Keyboard, Eye, EyeOff, Lock, Unlock, Search, Filter,
  PanelBottom, PanelLeft, PanelRight, PanelTop,
  Undo2, Redo2, GripVertical, X, Check, ChevronDown,
  ChevronRight, Plus, Minus, Trash2, Settings, FileDown,
  FileUp, Printer, Camera, Lasso, Paintbrush,
  type LucideIcon,
} from 'lucide-react'

export const FEATURE_ICONS: Record<string, LucideIcon> = {
  primitive: BoxSelect,
  extrude: Move3d,
  revolve: Rotate3d,
  sweep: Shuffle,
  loft: Layers,
  coil: Diamond,
  rib: Columns3,
  fillet: Radius,
  chamfer: Crop,
  shell: Shell,
  draft: Waves,
  hole: Drill,
  boolean: Combine,
  mirror: Crosshair,
  pattern: Component,
  emboss: CaseSensitive,
  wrap: WrapText,
  'split-body': Split,
  'move-face': Hand,
  suppress: Ban,
  sketch: Pencil,
  'mesh-edit': Shapes,
  sculpt: Paintbrush,
  'nurbs-curve': Spline,
  'nurbs-surface': Orbit,
  'sheet-metal': Pyramid,
  assembly: Cog,
  measure: Ruler,
  material: PaintBucket,
}

export const TOOL_ICONS: Record<string, LucideIcon> = {
  select: BoxSelect,
  move: Move3d,
  rotate: Rotate3d,
  scale: Maximize2,
  sketch: Pencil,
  extrude: Move3d,
  revolve: Rotate3d,
  sweep: Shuffle,
  loft: Layers,
  coil: Diamond,
  fillet: Radius,
  chamfer: Crop,
  shell: Shell,
  draft: Waves,
  hole: Drill,
  thread: Cog,
  boolean: Combine,
  mirror: Crosshair,
  pattern: Component,
  emboss: CaseSensitive,
  wrap: WrapText,
  'split-body': Split,
  'move-face': Hand,
  suppress: Ban,
  measure: Ruler,
  'mesh-vertex': Shapes,
  'mesh-edge': Rows3,
  'mesh-face': Columns2,
  sculpt: Paintbrush,
  'nurbs-curve': Spline,
  'nurbs-surface': Orbit,
  'sheet-metal': Pyramid,
  'assembly-joint': Cog,
  'assembly-mate': AlignCenter,
  material: PaintBucket,
  'section-view': Eye,
  'annotate-3d': Type,
  probe: Crosshair,
}

export {
  GripVertical, X, Check, ChevronDown, ChevronRight,
  Plus, Minus, Trash2, Settings, FileDown, FileUp,
  Printer, Camera, Lasso, Undo2, Redo2,
  Eye, EyeOff, Lock, Unlock, Search, Filter,
  PanelBottom, PanelLeft, PanelRight, PanelTop,
  Keyboard, Workflow, Variable, Type,
}
