// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-hero/LivingGrid.tsx": () => import("../components/mockups/landing-hero/LivingGrid.tsx"),
  "./components/mockups/landing-hero/TerminalBoot.tsx": () => import("../components/mockups/landing-hero/TerminalBoot.tsx"),
  "./components/mockups/landing-hero/TheVoid.tsx": () => import("../components/mockups/landing-hero/TheVoid.tsx")
};
