/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArduinoRouteImport } from './routes/arduino'
import { Route as ArdurinoRouteImport } from './routes/ardurino'
import { Route as AuthBridgeRouteImport } from './routes/auth-bridge'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as AuthLinkRouteImport } from './routes/auth-link'
import { Route as AuthLogoutRouteImport } from './routes/auth-logout'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as CadRouteImport } from './routes/cad'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as FtcRouteImport } from './routes/ftc'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LinkDiscordRouteImport } from './routes/link-discord'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OauthAppsRouteImport } from './routes/oauth-apps'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ScratchRouteImport } from './routes/scratch'
import { Route as TermsOfUseRouteImport } from './routes/terms-of-use'
import { Route as ThreadsRouteImport } from './routes/threads'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminOauthHostsRouteImport } from './routes/admin.oauth-hosts'
import { Route as AdminOnlineUsersRouteImport } from './routes/admin.online-users'
import { Route as AdminUsageRouteImport } from './routes/admin.usage'
import { Route as AuthExternalOauthRouteImport } from './routes/auth.external-oauth'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as LandingIndexRouteImport } from './routes/landing.index'
import { Route as LandingLivingGridRouteImport } from './routes/landing.living-grid'
import { Route as LandingMonochromeRouteImport } from './routes/landing.monochrome'
import { Route as LandingTerminalBootRouteImport } from './routes/landing.terminal-boot'
import { Route as LandingTerminalVerdictRouteImport } from './routes/landing.terminal-verdict'
import { Route as LandingTheVoidRouteImport } from './routes/landing.the-void'
import { Route as LandingWarmMomentumRouteImport } from './routes/landing.warm-momentum'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as ProjectProjectIdRouteImport } from './routes/project.$projectId'
import { Route as RedactorIndexRouteImport } from './routes/redactor.index'
import { Route as RedactorAuthenticatedRouteImport } from './routes/redactor._authenticated'
import { Route as RedactorAuthRouteImport } from './routes/redactor.auth'
import { Route as ThreadsIndexRouteImport } from './routes/threads.index'
import { Route as ThreadsIdRouteImport } from './routes/threads.$id'
import { Route as ThreadsNewRouteImport } from './routes/threads.new'
import { Route as ThreadsWhiteboardRouteImport } from './routes/threads.whiteboard'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as RedactorAuthenticatedDashboardRouteImport } from './routes/redactor._authenticated.dashboard'
import { Route as RedactorAuthenticatedLogsRouteImport } from './routes/redactor._authenticated.logs'
import { Route as RedactorAuthenticatedPlaygroundRouteImport } from './routes/redactor._authenticated.playground'
import { Route as RedactorAuthenticatedProviderKeysRouteImport } from './routes/redactor._authenticated.provider-keys'
import { Route as RedactorAuthenticatedProxyKeysRouteImport } from './routes/redactor._authenticated.proxy-keys'
import { Route as RedactorAuthenticatedRoutersRouteImport } from './routes/redactor._authenticated.routers'
import { Route as RedactorAuthenticatedRulesRouteImport } from './routes/redactor._authenticated.rules'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArduinoRoute = ArduinoRouteImport.update({
  id: '/arduino',
  path: '/arduino',
  getParentRoute: () => rootRouteImport,
} as any)
const ArdurinoRoute = ArdurinoRouteImport.update({
  id: '/ardurino',
  path: '/ardurino',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthBridgeRoute = AuthBridgeRouteImport.update({
  id: '/auth-bridge',
  path: '/auth-bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLinkRoute = AuthLinkRouteImport.update({
  id: '/auth-link',
  path: '/auth-link',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth-logout',
  path: '/auth-logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const CadRoute = CadRouteImport.update({
  id: '/cad',
  path: '/cad',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const FtcRoute = FtcRouteImport.update({
  id: '/ftc',
  path: '/ftc',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkDiscordRoute = LinkDiscordRouteImport.update({
  id: '/link-discord',
  path: '/link-discord',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthAppsRoute = OauthAppsRouteImport.update({
  id: '/oauth-apps',
  path: '/oauth-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ScratchRoute = ScratchRouteImport.update({
  id: '/scratch',
  path: '/scratch',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfUseRoute = TermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsRoute = ThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOauthHostsRoute = AdminOauthHostsRouteImport.update({
  id: '/admin/oauth-hosts',
  path: '/admin/oauth-hosts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOnlineUsersRoute = AdminOnlineUsersRouteImport.update({
  id: '/admin/online-users',
  path: '/admin/online-users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsageRoute = AdminUsageRouteImport.update({
  id: '/admin/usage',
  path: '/admin/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthExternalOauthRoute = AuthExternalOauthRouteImport.update({
  id: '/auth/external-oauth',
  path: '/auth/external-oauth',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/landing/',
  path: '/landing/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingLivingGridRoute = LandingLivingGridRouteImport.update({
  id: '/landing/living-grid',
  path: '/landing/living-grid',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingMonochromeRoute = LandingMonochromeRouteImport.update({
  id: '/landing/monochrome',
  path: '/landing/monochrome',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingTerminalBootRoute = LandingTerminalBootRouteImport.update({
  id: '/landing/terminal-boot',
  path: '/landing/terminal-boot',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingTerminalVerdictRoute = LandingTerminalVerdictRouteImport.update({
  id: '/landing/terminal-verdict',
  path: '/landing/terminal-verdict',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingTheVoidRoute = LandingTheVoidRouteImport.update({
  id: '/landing/the-void',
  path: '/landing/the-void',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingWarmMomentumRoute = LandingWarmMomentumRouteImport.update({
  id: '/landing/warm-momentum',
  path: '/landing/warm-momentum',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const RedactorIndexRoute = RedactorIndexRouteImport.update({
  id: '/redactor/',
  path: '/redactor/',
  getParentRoute: () => rootRouteImport,
} as any)
const RedactorAuthenticatedRoute = RedactorAuthenticatedRouteImport.update({
  id: '/redactor/_authenticated',
  path: '/redactor',
  getParentRoute: () => rootRouteImport,
} as any)
const RedactorAuthRoute = RedactorAuthRouteImport.update({
  id: '/redactor/auth',
  path: '/redactor/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsIndexRoute = ThreadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ThreadsRoute,
} as any)
const ThreadsIdRoute = ThreadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ThreadsRoute,
} as any)
const ThreadsNewRoute = ThreadsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ThreadsRoute,
} as any)
const ThreadsWhiteboardRoute = ThreadsWhiteboardRouteImport.update({
  id: '/whiteboard',
  path: '/whiteboard',
  getParentRoute: () => ThreadsRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const RedactorAuthenticatedDashboardRoute =
  RedactorAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => RedactorAuthenticatedRoute,
  } as any)
const RedactorAuthenticatedLogsRoute =
  RedactorAuthenticatedLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => RedactorAuthenticatedRoute,
  } as any)
const RedactorAuthenticatedPlaygroundRoute =
  RedactorAuthenticatedPlaygroundRouteImport.update({
    id: '/playground',
    path: '/playground',
    getParentRoute: () => RedactorAuthenticatedRoute,
  } as any)
const RedactorAuthenticatedProviderKeysRoute =
  RedactorAuthenticatedProviderKeysRouteImport.update({
    id: '/provider-keys',
    path: '/provider-keys',
    getParentRoute: () => RedactorAuthenticatedRoute,
  } as any)
const RedactorAuthenticatedProxyKeysRoute =
  RedactorAuthenticatedProxyKeysRouteImport.update({
    id: '/proxy-keys',
    path: '/proxy-keys',
    getParentRoute: () => RedactorAuthenticatedRoute,
  } as any)
const RedactorAuthenticatedRoutersRoute =
  RedactorAuthenticatedRoutersRouteImport.update({
    id: '/routers',
    path: '/routers',
    getParentRoute: () => RedactorAuthenticatedRoute,
  } as any)
const RedactorAuthenticatedRulesRoute =
  RedactorAuthenticatedRulesRouteImport.update({
    id: '/rules',
    path: '/rules',
    getParentRoute: () => RedactorAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arduino': typeof ArduinoRoute
  '/ardurino': typeof ArdurinoRoute
  '/auth-bridge': typeof AuthBridgeRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/auth-link': typeof AuthLinkRoute
  '/auth-logout': typeof AuthLogoutRoute
  '/automations': typeof AutomationsRoute
  '/cad': typeof CadRoute
  '/compare': typeof CompareRoute
  '/editor': typeof EditorRoute
  '/ftc': typeof FtcRoute
  '/home': typeof HomeRoute
  '/link-discord': typeof LinkDiscordRoute
  '/mcp': typeof McpRoute
  '/oauth-apps': typeof OauthAppsRoute
  '/office': typeof OfficeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scratch': typeof ScratchRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/threads': typeof ThreadsRouteWithChildren
  '/admin/oauth-hosts': typeof AdminOauthHostsRoute
  '/admin/online-users': typeof AdminOnlineUsersRoute
  '/admin/usage': typeof AdminUsageRoute
  '/auth/external-oauth': typeof AuthExternalOauthRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/landing/living-grid': typeof LandingLivingGridRoute
  '/landing/monochrome': typeof LandingMonochromeRoute
  '/landing/terminal-boot': typeof LandingTerminalBootRoute
  '/landing/terminal-verdict': typeof LandingTerminalVerdictRoute
  '/landing/the-void': typeof LandingTheVoidRoute
  '/landing/warm-momentum': typeof LandingWarmMomentumRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/redactor': typeof RedactorAuthenticatedRouteWithChildren
  '/redactor/auth': typeof RedactorAuthRoute
  '/threads/$id': typeof ThreadsIdRoute
  '/threads/new': typeof ThreadsNewRoute
  '/threads/whiteboard': typeof ThreadsWhiteboardRoute
  '/admin/': typeof AdminIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/landing/': typeof LandingIndexRoute
  '/redactor/': typeof RedactorIndexRoute
  '/threads/': typeof ThreadsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/redactor/dashboard': typeof RedactorAuthenticatedDashboardRoute
  '/redactor/logs': typeof RedactorAuthenticatedLogsRoute
  '/redactor/playground': typeof RedactorAuthenticatedPlaygroundRoute
  '/redactor/provider-keys': typeof RedactorAuthenticatedProviderKeysRoute
  '/redactor/proxy-keys': typeof RedactorAuthenticatedProxyKeysRoute
  '/redactor/routers': typeof RedactorAuthenticatedRoutersRoute
  '/redactor/rules': typeof RedactorAuthenticatedRulesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arduino': typeof ArduinoRoute
  '/ardurino': typeof ArdurinoRoute
  '/auth-bridge': typeof AuthBridgeRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/auth-link': typeof AuthLinkRoute
  '/auth-logout': typeof AuthLogoutRoute
  '/automations': typeof AutomationsRoute
  '/cad': typeof CadRoute
  '/compare': typeof CompareRoute
  '/editor': typeof EditorRoute
  '/ftc': typeof FtcRoute
  '/home': typeof HomeRoute
  '/link-discord': typeof LinkDiscordRoute
  '/mcp': typeof McpRoute
  '/oauth-apps': typeof OauthAppsRoute
  '/office': typeof OfficeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scratch': typeof ScratchRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/admin/oauth-hosts': typeof AdminOauthHostsRoute
  '/admin/online-users': typeof AdminOnlineUsersRoute
  '/admin/usage': typeof AdminUsageRoute
  '/auth/external-oauth': typeof AuthExternalOauthRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/landing/living-grid': typeof LandingLivingGridRoute
  '/landing/monochrome': typeof LandingMonochromeRoute
  '/landing/terminal-boot': typeof LandingTerminalBootRoute
  '/landing/terminal-verdict': typeof LandingTerminalVerdictRoute
  '/landing/the-void': typeof LandingTheVoidRoute
  '/landing/warm-momentum': typeof LandingWarmMomentumRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/redactor': typeof RedactorIndexRoute
  '/redactor/auth': typeof RedactorAuthRoute
  '/threads/$id': typeof ThreadsIdRoute
  '/threads/new': typeof ThreadsNewRoute
  '/threads/whiteboard': typeof ThreadsWhiteboardRoute
  '/admin': typeof AdminIndexRoute
  '/docs': typeof DocsIndexRoute
  '/landing': typeof LandingIndexRoute
  '/threads': typeof ThreadsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/redactor/dashboard': typeof RedactorAuthenticatedDashboardRoute
  '/redactor/logs': typeof RedactorAuthenticatedLogsRoute
  '/redactor/playground': typeof RedactorAuthenticatedPlaygroundRoute
  '/redactor/provider-keys': typeof RedactorAuthenticatedProviderKeysRoute
  '/redactor/proxy-keys': typeof RedactorAuthenticatedProxyKeysRoute
  '/redactor/routers': typeof RedactorAuthenticatedRoutersRoute
  '/redactor/rules': typeof RedactorAuthenticatedRulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arduino': typeof ArduinoRoute
  '/ardurino': typeof ArdurinoRoute
  '/auth-bridge': typeof AuthBridgeRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/auth-link': typeof AuthLinkRoute
  '/auth-logout': typeof AuthLogoutRoute
  '/automations': typeof AutomationsRoute
  '/cad': typeof CadRoute
  '/compare': typeof CompareRoute
  '/editor': typeof EditorRoute
  '/ftc': typeof FtcRoute
  '/home': typeof HomeRoute
  '/link-discord': typeof LinkDiscordRoute
  '/mcp': typeof McpRoute
  '/oauth-apps': typeof OauthAppsRoute
  '/office': typeof OfficeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scratch': typeof ScratchRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/threads': typeof ThreadsRouteWithChildren
  '/admin/oauth-hosts': typeof AdminOauthHostsRoute
  '/admin/online-users': typeof AdminOnlineUsersRoute
  '/admin/usage': typeof AdminUsageRoute
  '/auth/external-oauth': typeof AuthExternalOauthRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/landing/living-grid': typeof LandingLivingGridRoute
  '/landing/monochrome': typeof LandingMonochromeRoute
  '/landing/terminal-boot': typeof LandingTerminalBootRoute
  '/landing/terminal-verdict': typeof LandingTerminalVerdictRoute
  '/landing/the-void': typeof LandingTheVoidRoute
  '/landing/warm-momentum': typeof LandingWarmMomentumRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/redactor/_authenticated': typeof RedactorAuthenticatedRouteWithChildren
  '/redactor/auth': typeof RedactorAuthRoute
  '/threads/$id': typeof ThreadsIdRoute
  '/threads/new': typeof ThreadsNewRoute
  '/threads/whiteboard': typeof ThreadsWhiteboardRoute
  '/admin/': typeof AdminIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/landing/': typeof LandingIndexRoute
  '/redactor/': typeof RedactorIndexRoute
  '/threads/': typeof ThreadsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/redactor/_authenticated/dashboard': typeof RedactorAuthenticatedDashboardRoute
  '/redactor/_authenticated/logs': typeof RedactorAuthenticatedLogsRoute
  '/redactor/_authenticated/playground': typeof RedactorAuthenticatedPlaygroundRoute
  '/redactor/_authenticated/provider-keys': typeof RedactorAuthenticatedProviderKeysRoute
  '/redactor/_authenticated/proxy-keys': typeof RedactorAuthenticatedProxyKeysRoute
  '/redactor/_authenticated/routers': typeof RedactorAuthenticatedRoutersRoute
  '/redactor/_authenticated/rules': typeof RedactorAuthenticatedRulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arduino'
    | '/ardurino'
    | '/auth-bridge'
    | '/auth-callback'
    | '/auth-link'
    | '/auth-logout'
    | '/automations'
    | '/cad'
    | '/compare'
    | '/editor'
    | '/ftc'
    | '/home'
    | '/link-discord'
    | '/mcp'
    | '/oauth-apps'
    | '/office'
    | '/privacy-policy'
    | '/reset-password'
    | '/scratch'
    | '/terms-of-use'
    | '/threads'
    | '/admin/oauth-hosts'
    | '/admin/online-users'
    | '/admin/usage'
    | '/auth/external-oauth'
    | '/docs/$slug'
    | '/landing/living-grid'
    | '/landing/monochrome'
    | '/landing/terminal-boot'
    | '/landing/terminal-verdict'
    | '/landing/the-void'
    | '/landing/warm-momentum'
    | '/profile/$userId'
    | '/project/$projectId'
    | '/redactor'
    | '/redactor/auth'
    | '/threads/$id'
    | '/threads/new'
    | '/threads/whiteboard'
    | '/admin/'
    | '/docs/'
    | '/landing/'
    | '/redactor/'
    | '/threads/'
    | '/.lovable/oauth/consent'
    | '/redactor/dashboard'
    | '/redactor/logs'
    | '/redactor/playground'
    | '/redactor/provider-keys'
    | '/redactor/proxy-keys'
    | '/redactor/routers'
    | '/redactor/rules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arduino'
    | '/ardurino'
    | '/auth-bridge'
    | '/auth-callback'
    | '/auth-link'
    | '/auth-logout'
    | '/automations'
    | '/cad'
    | '/compare'
    | '/editor'
    | '/ftc'
    | '/home'
    | '/link-discord'
    | '/mcp'
    | '/oauth-apps'
    | '/office'
    | '/privacy-policy'
    | '/reset-password'
    | '/scratch'
    | '/terms-of-use'
    | '/admin/oauth-hosts'
    | '/admin/online-users'
    | '/admin/usage'
    | '/auth/external-oauth'
    | '/docs/$slug'
    | '/landing/living-grid'
    | '/landing/monochrome'
    | '/landing/terminal-boot'
    | '/landing/terminal-verdict'
    | '/landing/the-void'
    | '/landing/warm-momentum'
    | '/profile/$userId'
    | '/project/$projectId'
    | '/redactor'
    | '/redactor/auth'
    | '/threads/$id'
    | '/threads/new'
    | '/threads/whiteboard'
    | '/admin'
    | '/docs'
    | '/landing'
    | '/threads'
    | '/.lovable/oauth/consent'
    | '/redactor/dashboard'
    | '/redactor/logs'
    | '/redactor/playground'
    | '/redactor/provider-keys'
    | '/redactor/proxy-keys'
    | '/redactor/routers'
    | '/redactor/rules'
  id:
    | '__root__'
    | '/'
    | '/arduino'
    | '/ardurino'
    | '/auth-bridge'
    | '/auth-callback'
    | '/auth-link'
    | '/auth-logout'
    | '/automations'
    | '/cad'
    | '/compare'
    | '/editor'
    | '/ftc'
    | '/home'
    | '/link-discord'
    | '/mcp'
    | '/oauth-apps'
    | '/office'
    | '/privacy-policy'
    | '/reset-password'
    | '/scratch'
    | '/terms-of-use'
    | '/threads'
    | '/admin/oauth-hosts'
    | '/admin/online-users'
    | '/admin/usage'
    | '/auth/external-oauth'
    | '/docs/$slug'
    | '/landing/living-grid'
    | '/landing/monochrome'
    | '/landing/terminal-boot'
    | '/landing/terminal-verdict'
    | '/landing/the-void'
    | '/landing/warm-momentum'
    | '/profile/$userId'
    | '/project/$projectId'
    | '/redactor/_authenticated'
    | '/redactor/auth'
    | '/threads/$id'
    | '/threads/new'
    | '/threads/whiteboard'
    | '/admin/'
    | '/docs/'
    | '/landing/'
    | '/redactor/'
    | '/threads/'
    | '/.lovable/oauth/consent'
    | '/redactor/_authenticated/dashboard'
    | '/redactor/_authenticated/logs'
    | '/redactor/_authenticated/playground'
    | '/redactor/_authenticated/provider-keys'
    | '/redactor/_authenticated/proxy-keys'
    | '/redactor/_authenticated/routers'
    | '/redactor/_authenticated/rules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArduinoRoute: typeof ArduinoRoute
  ArdurinoRoute: typeof ArdurinoRoute
  AuthBridgeRoute: typeof AuthBridgeRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLinkRoute: typeof AuthLinkRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AutomationsRoute: typeof AutomationsRoute
  CadRoute: typeof CadRoute
  CompareRoute: typeof CompareRoute
  EditorRoute: typeof EditorRoute
  FtcRoute: typeof FtcRoute
  HomeRoute: typeof HomeRoute
  LinkDiscordRoute: typeof LinkDiscordRoute
  McpRoute: typeof McpRoute
  OauthAppsRoute: typeof OauthAppsRoute
  OfficeRoute: typeof OfficeRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScratchRoute: typeof ScratchRoute
  TermsOfUseRoute: typeof TermsOfUseRoute
  ThreadsRoute: typeof ThreadsRouteWithChildren
  AdminOauthHostsRoute: typeof AdminOauthHostsRoute
  AdminOnlineUsersRoute: typeof AdminOnlineUsersRoute
  AdminUsageRoute: typeof AdminUsageRoute
  AuthExternalOauthRoute: typeof AuthExternalOauthRoute
  DocsSlugRoute: typeof DocsSlugRoute
  LandingLivingGridRoute: typeof LandingLivingGridRoute
  LandingMonochromeRoute: typeof LandingMonochromeRoute
  LandingTerminalBootRoute: typeof LandingTerminalBootRoute
  LandingTerminalVerdictRoute: typeof LandingTerminalVerdictRoute
  LandingTheVoidRoute: typeof LandingTheVoidRoute
  LandingWarmMomentumRoute: typeof LandingWarmMomentumRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
  RedactorAuthenticatedRoute: typeof RedactorAuthenticatedRouteWithChildren
  RedactorAuthRoute: typeof RedactorAuthRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  LandingIndexRoute: typeof LandingIndexRoute
  RedactorIndexRoute: typeof RedactorIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arduino': {
      id: '/arduino'
      path: '/arduino'
      fullPath: '/arduino'
      preLoaderRoute: typeof ArduinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ardurino': {
      id: '/ardurino'
      path: '/ardurino'
      fullPath: '/ardurino'
      preLoaderRoute: typeof ArdurinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-bridge': {
      id: '/auth-bridge'
      path: '/auth-bridge'
      fullPath: '/auth-bridge'
      preLoaderRoute: typeof AuthBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-link': {
      id: '/auth-link'
      path: '/auth-link'
      fullPath: '/auth-link'
      preLoaderRoute: typeof AuthLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-logout': {
      id: '/auth-logout'
      path: '/auth-logout'
      fullPath: '/auth-logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cad': {
      id: '/cad'
      path: '/cad'
      fullPath: '/cad'
      preLoaderRoute: typeof CadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ftc': {
      id: '/ftc'
      path: '/ftc'
      fullPath: '/ftc'
      preLoaderRoute: typeof FtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link-discord': {
      id: '/link-discord'
      path: '/link-discord'
      fullPath: '/link-discord'
      preLoaderRoute: typeof LinkDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-apps': {
      id: '/oauth-apps'
      path: '/oauth-apps'
      fullPath: '/oauth-apps'
      preLoaderRoute: typeof OauthAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scratch': {
      id: '/scratch'
      path: '/scratch'
      fullPath: '/scratch'
      preLoaderRoute: typeof ScratchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-use': {
      id: '/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof TermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads': {
      id: '/threads'
      path: '/threads'
      fullPath: '/threads'
      preLoaderRoute: typeof ThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/oauth-hosts': {
      id: '/admin/oauth-hosts'
      path: '/admin/oauth-hosts'
      fullPath: '/admin/oauth-hosts'
      preLoaderRoute: typeof AdminOauthHostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/online-users': {
      id: '/admin/online-users'
      path: '/admin/online-users'
      fullPath: '/admin/online-users'
      preLoaderRoute: typeof AdminOnlineUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usage': {
      id: '/admin/usage'
      path: '/admin/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AdminUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/external-oauth': {
      id: '/auth/external-oauth'
      path: '/auth/external-oauth'
      fullPath: '/auth/external-oauth'
      preLoaderRoute: typeof AuthExternalOauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/': {
      id: '/landing/'
      path: '/landing'
      fullPath: '/landing/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/living-grid': {
      id: '/landing/living-grid'
      path: '/landing/living-grid'
      fullPath: '/landing/living-grid'
      preLoaderRoute: typeof LandingLivingGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/monochrome': {
      id: '/landing/monochrome'
      path: '/landing/monochrome'
      fullPath: '/landing/monochrome'
      preLoaderRoute: typeof LandingMonochromeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/terminal-boot': {
      id: '/landing/terminal-boot'
      path: '/landing/terminal-boot'
      fullPath: '/landing/terminal-boot'
      preLoaderRoute: typeof LandingTerminalBootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/terminal-verdict': {
      id: '/landing/terminal-verdict'
      path: '/landing/terminal-verdict'
      fullPath: '/landing/terminal-verdict'
      preLoaderRoute: typeof LandingTerminalVerdictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/the-void': {
      id: '/landing/the-void'
      path: '/landing/the-void'
      fullPath: '/landing/the-void'
      preLoaderRoute: typeof LandingTheVoidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/warm-momentum': {
      id: '/landing/warm-momentum'
      path: '/landing/warm-momentum'
      fullPath: '/landing/warm-momentum'
      preLoaderRoute: typeof LandingWarmMomentumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redactor/': {
      id: '/redactor/'
      path: '/redactor'
      fullPath: '/redactor/'
      preLoaderRoute: typeof RedactorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redactor/_authenticated': {
      id: '/redactor/_authenticated'
      path: '/redactor'
      fullPath: '/redactor'
      preLoaderRoute: typeof RedactorAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redactor/auth': {
      id: '/redactor/auth'
      path: '/redactor/auth'
      fullPath: '/redactor/auth'
      preLoaderRoute: typeof RedactorAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/': {
      id: '/threads/'
      path: '/'
      fullPath: '/threads/'
      preLoaderRoute: typeof ThreadsIndexRouteImport
      parentRoute: typeof ThreadsRoute
    }
    '/threads/$id': {
      id: '/threads/$id'
      path: '/$id'
      fullPath: '/threads/$id'
      preLoaderRoute: typeof ThreadsIdRouteImport
      parentRoute: typeof ThreadsRoute
    }
    '/threads/new': {
      id: '/threads/new'
      path: '/new'
      fullPath: '/threads/new'
      preLoaderRoute: typeof ThreadsNewRouteImport
      parentRoute: typeof ThreadsRoute
    }
    '/threads/whiteboard': {
      id: '/threads/whiteboard'
      path: '/whiteboard'
      fullPath: '/threads/whiteboard'
      preLoaderRoute: typeof ThreadsWhiteboardRouteImport
      parentRoute: typeof ThreadsRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redactor/_authenticated/dashboard': {
      id: '/redactor/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/redactor/dashboard'
      preLoaderRoute: typeof RedactorAuthenticatedDashboardRouteImport
      parentRoute: typeof RedactorAuthenticatedRoute
    }
    '/redactor/_authenticated/logs': {
      id: '/redactor/_authenticated/logs'
      path: '/logs'
      fullPath: '/redactor/logs'
      preLoaderRoute: typeof RedactorAuthenticatedLogsRouteImport
      parentRoute: typeof RedactorAuthenticatedRoute
    }
    '/redactor/_authenticated/playground': {
      id: '/redactor/_authenticated/playground'
      path: '/playground'
      fullPath: '/redactor/playground'
      preLoaderRoute: typeof RedactorAuthenticatedPlaygroundRouteImport
      parentRoute: typeof RedactorAuthenticatedRoute
    }
    '/redactor/_authenticated/provider-keys': {
      id: '/redactor/_authenticated/provider-keys'
      path: '/provider-keys'
      fullPath: '/redactor/provider-keys'
      preLoaderRoute: typeof RedactorAuthenticatedProviderKeysRouteImport
      parentRoute: typeof RedactorAuthenticatedRoute
    }
    '/redactor/_authenticated/proxy-keys': {
      id: '/redactor/_authenticated/proxy-keys'
      path: '/proxy-keys'
      fullPath: '/redactor/proxy-keys'
      preLoaderRoute: typeof RedactorAuthenticatedProxyKeysRouteImport
      parentRoute: typeof RedactorAuthenticatedRoute
    }
    '/redactor/_authenticated/routers': {
      id: '/redactor/_authenticated/routers'
      path: '/routers'
      fullPath: '/redactor/routers'
      preLoaderRoute: typeof RedactorAuthenticatedRoutersRouteImport
      parentRoute: typeof RedactorAuthenticatedRoute
    }
    '/redactor/_authenticated/rules': {
      id: '/redactor/_authenticated/rules'
      path: '/rules'
      fullPath: '/redactor/rules'
      preLoaderRoute: typeof RedactorAuthenticatedRulesRouteImport
      parentRoute: typeof RedactorAuthenticatedRoute
    }
  }
}

interface ThreadsRouteChildren {
  ThreadsIdRoute: typeof ThreadsIdRoute
  ThreadsNewRoute: typeof ThreadsNewRoute
  ThreadsWhiteboardRoute: typeof ThreadsWhiteboardRoute
  ThreadsIndexRoute: typeof ThreadsIndexRoute
}

const ThreadsRouteChildren: ThreadsRouteChildren = {
  ThreadsIdRoute: ThreadsIdRoute,
  ThreadsNewRoute: ThreadsNewRoute,
  ThreadsWhiteboardRoute: ThreadsWhiteboardRoute,
  ThreadsIndexRoute: ThreadsIndexRoute,
}

const ThreadsRouteWithChildren =
  ThreadsRoute._addFileChildren(ThreadsRouteChildren)

interface RedactorAuthenticatedRouteChildren {
  RedactorAuthenticatedDashboardRoute: typeof RedactorAuthenticatedDashboardRoute
  RedactorAuthenticatedLogsRoute: typeof RedactorAuthenticatedLogsRoute
  RedactorAuthenticatedPlaygroundRoute: typeof RedactorAuthenticatedPlaygroundRoute
  RedactorAuthenticatedProviderKeysRoute: typeof RedactorAuthenticatedProviderKeysRoute
  RedactorAuthenticatedProxyKeysRoute: typeof RedactorAuthenticatedProxyKeysRoute
  RedactorAuthenticatedRoutersRoute: typeof RedactorAuthenticatedRoutersRoute
  RedactorAuthenticatedRulesRoute: typeof RedactorAuthenticatedRulesRoute
}

const RedactorAuthenticatedRouteChildren: RedactorAuthenticatedRouteChildren = {
  RedactorAuthenticatedDashboardRoute: RedactorAuthenticatedDashboardRoute,
  RedactorAuthenticatedLogsRoute: RedactorAuthenticatedLogsRoute,
  RedactorAuthenticatedPlaygroundRoute: RedactorAuthenticatedPlaygroundRoute,
  RedactorAuthenticatedProviderKeysRoute:
    RedactorAuthenticatedProviderKeysRoute,
  RedactorAuthenticatedProxyKeysRoute: RedactorAuthenticatedProxyKeysRoute,
  RedactorAuthenticatedRoutersRoute: RedactorAuthenticatedRoutersRoute,
  RedactorAuthenticatedRulesRoute: RedactorAuthenticatedRulesRoute,
}

const RedactorAuthenticatedRouteWithChildren =
  RedactorAuthenticatedRoute._addFileChildren(
    RedactorAuthenticatedRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArduinoRoute: ArduinoRoute,
  ArdurinoRoute: ArdurinoRoute,
  AuthBridgeRoute: AuthBridgeRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLinkRoute: AuthLinkRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AutomationsRoute: AutomationsRoute,
  CadRoute: CadRoute,
  CompareRoute: CompareRoute,
  EditorRoute: EditorRoute,
  FtcRoute: FtcRoute,
  HomeRoute: HomeRoute,
  LinkDiscordRoute: LinkDiscordRoute,
  McpRoute: McpRoute,
  OauthAppsRoute: OauthAppsRoute,
  OfficeRoute: OfficeRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScratchRoute: ScratchRoute,
  TermsOfUseRoute: TermsOfUseRoute,
  ThreadsRoute: ThreadsRouteWithChildren,
  AdminOauthHostsRoute: AdminOauthHostsRoute,
  AdminOnlineUsersRoute: AdminOnlineUsersRoute,
  AdminUsageRoute: AdminUsageRoute,
  AuthExternalOauthRoute: AuthExternalOauthRoute,
  DocsSlugRoute: DocsSlugRoute,
  LandingLivingGridRoute: LandingLivingGridRoute,
  LandingMonochromeRoute: LandingMonochromeRoute,
  LandingTerminalBootRoute: LandingTerminalBootRoute,
  LandingTerminalVerdictRoute: LandingTerminalVerdictRoute,
  LandingTheVoidRoute: LandingTheVoidRoute,
  LandingWarmMomentumRoute: LandingWarmMomentumRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  ProjectProjectIdRoute: ProjectProjectIdRoute,
  RedactorAuthenticatedRoute: RedactorAuthenticatedRouteWithChildren,
  RedactorAuthRoute: RedactorAuthRoute,
  AdminIndexRoute: AdminIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  LandingIndexRoute: LandingIndexRoute,
  RedactorIndexRoute: RedactorIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
