// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-public-canvases.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function supabase() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_public_canvases_default = defineTool({
  name: "search_public_canvases",
  title: "Search public canvases",
  description: "Search public CodeCanvas projects by name, description, or language. Returns up to 20 results ordered by stars.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Free-text query matched against name, description, and language."),
    limit: z.number().int().min(1).max(20).optional().describe("Maximum number of results (default 10, max 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const { data, error } = await supabase().from("projects").select("id, name, description, language, stars_count, updated_at").eq("is_public", true).or(`name.ilike.%${query}%,description.ilike.%${query}%,language.ilike.%${query}%`).order("stars_count", { ascending: false }).limit(limit ?? 10);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-featured-canvases.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabase2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_featured_canvases_default = defineTool2({
  name: "get_featured_canvases",
  title: "Get featured canvases",
  description: "Return the top public CodeCanvas projects ordered by star count.",
  inputSchema: {
    limit: z2.number().int().min(1).max(20).optional().describe("How many featured canvases to return (default 5, max 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const { data, error } = await supabase2().from("projects").select("id, name, description, language, stars_count, updated_at").eq("is_public", true).order("stars_count", { ascending: false }).limit(limit ?? 5);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-canvas-count.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabase3() {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_canvas_count_default = defineTool3({
  name: "get_canvas_count",
  title: "Get total canvas count",
  description: "Return the total number of CodeCanvas projects across the platform.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const { data, error } = await supabase3().rpc("get_total_canvases_count");
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const count = typeof data === "number" ? data : Number(data ?? 0);
    return {
      content: [{ type: "text", text: `Total canvases: ${count}` }],
      structuredContent: { count }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "codecanvas-mcp",
  title: "CodeCanvas MCP",
  version: "0.1.0",
  instructions: "Tools for exploring public CodeCanvas projects. Use `search_public_canvases` to find canvases by keyword, `get_featured_canvases` for the top-starred canvases, and `get_canvas_count` for the total number of canvases on the platform.",
  tools: [search_public_canvases_default, get_featured_canvases_default, get_canvas_count_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
