// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// In Discord's CSP-restricted iframe, route Supabase calls through our server proxy
// to avoid being blocked by Discord's Content Security Policy.
const isDiscordIframe = typeof window !== 'undefined' && (() => {
  try { return window.self !== window.top; } catch { return true; }
})();

const effectiveUrl = isDiscordIframe ? '/api/supabase' : SUPABASE_URL;

export const supabase = createClient<Database>(effectiveUrl, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});